### ISSUE TITLE
[TODO] Clean Marc's Default Content

### ISSUE THREAD

**Issue by fabie37** [marcaufderheyde/cannabisclubsberlin.com#3]
## To Do: Clean Marc's Default Content
Since we are looking to redo the site a bit - we should probably start with a clean repository. If we ever need the assets again, we can always revert back cause we are using github.

## Check List

- [ ]  Clean App Folder: rm about, clubs, components, contant, imprint, termsofuse
- [ ]  Clean page.tsx page
- [ ] Update .gitignore to ignore build files and remove tracking for build directories.
